### ISSUE TITLE
[Windows] [Linux] The tracker text is not vertically aligned with the rest of the newtab elements

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [biancadanforth/tracking-protection-shield-study#177] opened 2018-03-13 16:48 UTC
[Affected versions]:
- Unbranded Beta 59.0b14

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have the latest Tracking Protection Messaging .xpi installed (v.1.0.3)

[Steps to reproduce]:
1. Open the browser and navigate to a website (e.g. www.cnn.com).
2. Open a new tab and observe the tracker text.

[Expected result]:
- The tracker text is vertically aligned with the rest of the newtab elements.

[Actual result]:
- The tracker text is not vertically aligned with the rest of the newtab elements.

[Notes]:
- This is reproducible with both "fast" and "private" variants.
- On MacOS, the tracker text is vertically aligned with the rest of the elements.
- Attached a screenshot of the issue:

![misaligned](https://user-images.githubusercontent.com/26000308/37356586-050891b6-26ef-11e8-9a05-dd4fc7178d61.png)

**Comment by biancadanforth** [comment] 2018-03-13 17:15
Thanks Carmen for finding this. That's a little odd. I tested it on Linux and felt I needed to add some padding and margin to get it aligned. I'll check again.

**Comment by biancadanforth** [comment] 2018-03-14 04:03
Hmm... I can't reproduce this issue on Linux or Windows. I actually added padding to fix this already for #138 . You can see the before/after pictures for the Windows/Linux `about:newtab` in the corresponding PR, PR #158 .

For some reason, your version of Windows and Linux does not have the extra padding, whereas mine does.

Here's an example of how I see things on Windows (Linux was similar):

Now:
![windows177](https://user-images.githubusercontent.com/17437436/37382646-143aa216-2701-11e8-8f8c-bad2a9f52657.PNG)

If I revert the change from #138 : 
![windows177without](https://user-images.githubusercontent.com/17437436/37382641-0ec2aa86-2701-11e8-8e49-3caf0b858969.PNG)

I thought perhaps it had something to do with the fact that I was using a pseudo-element (`::before`) to render the SVG icon in the new tab page, but I just changed it to be a `<span>`, and it had no effect (PR #183 ).

I'd say it's better for this to be indented inward rather than outward if there is going to be some discrepancy. And since I can't reproduce what you're seeing, and if I fix it for you, it becomes outdented for me, I'd say I'll leave it as is as a WONTFIX.

**Closed** 2018-03-14 10:47 UTC
Labels: P3

**Comment by biancadanforth** [comment] 2018-03-14 10:51
I wasn't testing on 59. Actually this was a real bug. Just fixed it. Thanks!

**Comment by SoftVision-EmilPasca** [comment] 2018-03-14 15:03
This issue is no longer reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.5), retested on Windows 10 x64, Mac OS 10.13 and Ubuntu 16.04 with Unbranded Beta 59.0b14.
