### ISSUE TITLE
Tracking protection prompt still shows on new tab page after disabling tracking protection

### ISSUE THREAD

**Issue by pdehaan** [biancadanforth/tracking-protection-shield-study#54] opened 2018-01-22 23:24 UTC
### Steps to reproduce:

1. Run `npm run firefox`.
1. Go to about:config
1. Set `extensions.tracking_protection_messaging_study.variation_override` to `private`.
1. Disable the add-on and re-load it in about:debugging (since you must set this preference before installing the study).
1. Go to http://cnn.com, http://msn.com, and http://msnbc.com (which should stop like 82 trackers).
1. Open a new tab.
1. Note the header text.
1. Disable the tracking protection shield study from the address bar.
1. Open a new tab.
1. Note the header text.

### Actual results:

After disabling tracking protection, I still see the Shield study text.

<img width="1280" alt="new_tab" src="https://user-images.githubusercontent.com/557895/35249740-0085aa90-ff88-11e7-9c6b-c731f8ad6e24.png">

**Comment by biancadanforth** [comment] 2018-01-23 17:54
Confirmed bug. Will fix this very soon.

Also, I just discovered this: you can actually add the override pref into ./test/utils.js to the list of `FIREFOX_PREFERENCES` to override the treatment on the first install via `npm run firefox`:

```
"extensions.tracking_protection_messaging_study.variation_override": "private",
```

You just have to remember to remove it again.

**Comment by biancadanforth** [comment] 2018-01-30 04:59
This is a duplicate of #39 .

**Closed by biancadanforth** 2018-01-30 04:59 UTC
Labels: bug
